### Upload Attach
POST http://localhost:8080/api/receipts/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="chrek.jpg"
Content-Type: image/jpeg

< E:\PHOTOS\chrek.jpg
